/* src/components/timer/PlantData.js */

export const PLANT_STAGES = [
    { level: 0, emoji: "🌱", label: "Seed", cost: 0 },
    { level: 1, emoji: "🌿", label: "Sprout", cost: 10 },
    { level: 2, emoji: "🪴", label: "Growing", cost: 10 },
    { level: 3, emoji: "🌷", label: "Flower", cost: 10 },
];

export const PLANT_TYPES = {
    // --- Flowers (12) ---
    tulip: { name: "Tulip", emoji: "🌷", description: "Symbol of deep love.", rarity: "Sprout", color: "#e8f5e9" },
    sunflower: { name: "Sunflower", emoji: "🌻", description: "Always facing the sun.", rarity: "Sprout", color: "#f1f8e9" },
    rose: { name: "Rose", emoji: "🌹", description: "Beautiful but thorny.", rarity: "Sprout", color: "#f9fbe7" },
    daisy: { name: "Daisy", emoji: "🌼", description: "Symbol of innocence.", rarity: "Sprout", color: "#fff9c4" },
    lily: { name: "Lily", rarity: "Leaf", emoji: "💮", description: "Purity and rebirth.", color: "#f0f4c3" },
    hibiscus: { name: "Hibiscus", emoji: "🌺", description: "Delicate beauty.", rarity: "Leaf", color: "#f8bbd0" },
    lotus: { name: "Lotus", emoji: "🪷", description: "Eloquence and peace.", rarity: "Flower", color: "#f3e5f5" },
    hyacinth: { name: "Hyacinth", emoji: "🪻", description: "Constancy of love.", rarity: "Flower", color: "#e1bee7" },
    cherry_blossom: { name: "Cherry Blossom", emoji: "🌸", description: "Spring is here.", rarity: "Flower", color: "#ffebee" },
    bouquet: { name: "Bouquet", emoji: "💐", description: "A gift of nature.", rarity: "Ancient", color: "#d1c4e9" },
    rosette: { name: "Rosette", emoji: "🏵️", description: "Excellence and glory.", rarity: "Ancient", color: "#fff59d" },
    wilted_flower: { name: "Wilted Flower", emoji: "🥀", description: "Fading memories.", rarity: "Ancient", color: "#cfd8dc" },

    // --- Trees & Foliage (15) ---
    seedling: { name: "Seedling", emoji: "🌱", description: "New beginnings.", rarity: "Sprout", color: "#f1f8e9" },
    potted_plant: { name: "Potted Plant", emoji: "🪴", description: "Indoor companion.", rarity: "Sprout", color: "#f0f4c3" },
    herb: { name: "Herb", emoji: "🌿", description: "Aromatic and useful.", rarity: "Sprout", color: "#dcedc8" },
    shamrock: { name: "Shamrock", emoji: "☘️", description: "Heart's ease.", rarity: "Leaf", color: "#c8e6c9" },
    clover: { name: "Clover", emoji: "🍀", description: "Luck of the garden.", rarity: "Leaf", color: "#a5d6a7" },
    leaf_wind: { name: "Windy Leaf", emoji: "🍃", description: "Whispering breeze.", rarity: "Leaf", color: "#e8f5e9" },
    maple: { name: "Maple", emoji: "🍁", description: "Autumn's warmth.", rarity: "Leaf", color: "#ffe0b2" },
    fallen_leaf: { name: "Fallen Leaf", emoji: "🍂", description: "Cycle of life.", rarity: "Leaf", color: "#d7ccc8" },
    bamboo: { name: "Bamboo", emoji: "🎋", description: "Wishes of progress.", rarity: "Flower", color: "#e0f2f1" },
    pine: { name: "Pine", emoji: "🌲", description: "Steady and strong.", rarity: "Flower", color: "#c8e6c9" },
    evergreen: { name: "Tree", emoji: "🌳", description: "Shade of wisdom.", rarity: "Flower", color: "#dcedc8" },
    palm: { name: "Palm", emoji: "🌴", description: "Tropical vibes.", rarity: "Flower", color: "#e1f5fe" },
    cactus: { name: "Cactus", emoji: "🌵", description: "Thriving in silence.", rarity: "Ancient", color: "#f1f8e9" },
    bamboo_pot: { name: "Pine Deco", emoji: "🎍", description: "Prosperous year.", rarity: "Ancient", color: "#f9fbe7" },
    rice: { name: "Rice Sheaf", emoji: "🌾", description: "Harvest's bounty.", rarity: "Ancient", color: "#fff3e0" },

    // --- Fruits (20) ---
    grapes: { name: "Grapes", emoji: "🍇", description: "Wild sweetness.", rarity: "Sprout", color: "#f3e5f5" },
    melon: { name: "Melon", emoji: "🍈", description: "Giant treat.", rarity: "Sprout", color: "#f1f8e9" },
    watermelon: { name: "Watermelon", emoji: "🍉", description: "Summer's gift.", rarity: "Sprout", color: "#ffebee" },
    tangerine: { name: "Tangerine", emoji: "🍊", description: "Burst of energy.", rarity: "Sprout", color: "#fff3e0" },
    lemon: { name: "Lemon", emoji: "🍋", description: "Zest for life.", rarity: "Sprout", color: "#fffde7" },
    lime: { name: "Lime", emoji: "🍋‍🟩", description: "Tangy surprise.", rarity: "Leaf", color: "#f0f4c3" },
    banana: { name: "Banana", emoji: "🍌", description: "Morning fuel.", rarity: "Leaf", color: "#fff9c4" },
    pineapple: { name: "Pineapple", emoji: "🍍", description: "King of fruits.", rarity: "Leaf", color: "#fff8e1" },
    mango: { name: "Mango", emoji: "🥭", description: "Tropical dream.", rarity: "Leaf", color: "#ffecb3" },
    apple: { name: "Red Apple", emoji: "🍎", description: "Classic crunch.", rarity: "Leaf", color: "#ffebee" },
    green_apple: { name: "Green Apple", emoji: "🍏", description: "Sour and crisp.", rarity: "Flower", color: "#f1f8e9" },
    pear: { name: "Pear", emoji: "🍐", description: "Elegant sweetness.", rarity: "Flower", color: "#f9fbe7" },
    peach: { name: "Peach", emoji: "🍑", description: "Soft and fuzzy.", rarity: "Flower", color: "#fff3e0" },
    cherries: { name: "Cherries", emoji: "🍒", description: "Double joy.", rarity: "Flower", color: "#ffebee" },
    strawberry: { name: "Strawberry", emoji: "🍓", description: "Berry sweet.", rarity: "Flower", color: "#ffebee" },
    blueberries: { name: "Blueberries", emoji: "🫐", description: "Deep focus.", rarity: "Ancient", color: "#e1f5fe" },
    kiwi: { name: "Kiwi", emoji: "🥝", description: "Tiny seeds.", rarity: "Ancient", color: "#f1f8e9" },
    tomato: { name: "Tomato", emoji: "🍅", description: "Garden's ruby.", rarity: "Ancient", color: "#ffebee" },
    olive: { name: "Olive", emoji: "🫒", description: "Peace offering.", rarity: "Ancient", color: "#f0f4c3" },
    coconut: { name: "Coconut", emoji: "🥥", description: "Hard shell, soft heart.", rarity: "Ancient", color: "#efebe9" },

    // --- Vegetables & Rare Finds (20) ---
    avocado: { name: "Avocado", emoji: "🥑", description: "Creamy treasure.", rarity: "Sprout", color: "#f1f8e9" },
    eggplant: { name: "Eggplant", emoji: "🍆", description: "Deep purple.", rarity: "Sprout", color: "#f3e5f5" },
    potato: { name: "Potato", emoji: "🥔", description: "Earthly soul.", rarity: "Sprout", color: "#efebe9" },
    carrot: { name: "Carrot", emoji: "🥕", description: "Bright vision.", rarity: "Sprout", color: "#fff3e0" },
    corn: { name: "Corn", emoji: "🌽", description: "Golden grain.", rarity: "Sprout", color: "#fff9c4" },
    pepper: { name: "Hot Pepper", emoji: "🌶️", description: "Spicy spark.", rarity: "Leaf", color: "#ffebee" },
    bell_pepper: { name: "Bell Pepper", emoji: "🫑", description: "Crunchy bell.", rarity: "Leaf", color: "#f1f8e9" },
    cucumber: { name: "Cucumber", emoji: "🥒", description: "Cooling down.", rarity: "Leaf", color: "#e8f5e9" },
    leafy_green: { name: "Leafy Green", emoji: "🥬", description: "Vibrant health.", rarity: "Leaf", color: "#c8e6c9" },
    broccoli: { name: "Broccoli", emoji: "🥦", description: "Mini forest.", rarity: "Leaf", color: "#dcedc8" },
    garlic: { name: "Garlic", emoji: "🧄", description: "Strong protection.", rarity: "Flower", color: "#f5f5f5" },
    onion: { name: "Onion", emoji: "🧅", description: "Lyrical layers.", rarity: "Flower", color: "#fce4ec" },
    mushroom: { name: "Mushroom", emoji: "🍄", description: "Magic spore.", rarity: "Flower", color: "#ffebee" },
    brown_mushroom: { name: "Rare Mushroom", emoji: "🍄‍🟫", description: "Forest hidden gem.", rarity: "Flower", color: "#d7ccc8" },
    peanuts: { name: "Peanuts", emoji: "🥜", description: "Nutty prize.", rarity: "Flower", color: "#fff3e0" },
    beans: { name: "Beans", emoji: "🫘", description: "Tiny power.", rarity: "Ancient", color: "#d7ccc8" },
    chestnut: { name: "Chestnut", emoji: "🌰", description: "Autumn nut.", rarity: "Ancient", color: "#efebe9" },
    pea_pod: { name: "Pea Pod", emoji: "🫛", description: "Peas in a pod.", rarity: "Ancient", color: "#f1f8e9" },
    ginger: { name: "Ginger", emoji: "🫚", description: "Fiery root.", rarity: "Ancient", color: "#f9fbe7" },
    sweet_potato: { name: "Sweet Potato", emoji: "🍠", description: "Cozy winter.", rarity: "Ancient", color: "#ede7f6" },
};
